apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: springboot-pipeline
  namespace: default
  annotations:
    backstage.io/ci-cd: enabled     # Enables Backstage integration
    tekton.dev/version: v1beta1    # Custom version annotation
    owner: team-devops             # Owner of the pipeline
    purpose: build-deploy
    backstage.io/kubernetes-id: springboot-pipeline  # Backstage ID to link the pipeline
    tektonci/enabled: 'true'                         # Enables Tekton CI/CD integration in Backstage
    tektonci/namespace: default                         # Namespace for the pipeline
spec:
  params:
    - name: repo_url
      type: string
    - name: image
      type: string
    - name: deployment_manifest
      type: string
    # - name: helm_chart
    #   type: string
    - name: namespace
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: repo_url
          value: $(params.repo_url)
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-app
      taskRef:
        name: build-app
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: docker-build-and-push
      taskRef:
        name: docker-build-and-push
      params:
        - name: image
          value: $(params.image)
      runAfter:
        - build-app
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: deploy-to-aks
      taskRef:
        name: deploy-to-aks
      params:
        - name: deployment_manifest
          value: $(params.deployment_manifest)
        # - name: helm_chart
        #   value: $(params.helm_chart)
        - name: namespace
          value: $(params.namespace)
        - name: image
          value: $(params.image)
      runAfter:
        - docker-build-and-push
      workspaces:
        - name: source
          workspace: shared-workspace
