apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: springboot-pipeline-run
  labels:
    tekton.dev/pipelines: "demo/springboot-pipeline"
spec:
  pipelineRef:
    name: springboot-pipeline
  serviceAccountName: tekton-sa
  params:
    - name: repo_url
      value: "https://github.com/rohit7533/pet-clinic.git"
    - name: image
      value: "idpdeveacr.azurecr.io/pet-clinic:latest"
    - name: deployment_manifest
      value: "/workspace/source/k8s/springboot-deploy.yaml"
    # - name: helm_chart
    #   value: "charts/springboot"
    - name: namespace
      value: "demo"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
