apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: springboot-pipeline-run
  namespace: default
  annotations:
    backstage.io/ci-cd: enabled     # Enables Backstage integration
    tekton.dev/version: v1beta1    # Custom version annotation
    owner: team-devops             # Owner of the pipeline
    purpose: build-deploy
    backstage.io/kubernetes-id: springboot-pipeline  # Backstage ID to link the pipeline
    tektonci/enabled: 'true'                         # Enables Tekton CI/CD integration in Backstage
    tektonci/namespace: default                         # Namespace for the pipeline
spec:
  pipelineRef:
    name: springboot-pipeline
  serviceAccountName: tekton-sa
  params:
    - name: repo_url
      value: "https://github.com/rohit7533/pet-clinic.git"
    - name: image
      value: "idpdeveacr.azurecr.io/pet-clinic:latest"
    - name: deployment_manifest
      value: "/workspace/source/k8s/springboot-deploy.yaml"
    # - name: helm_chart
    #   value: "charts/springboot"
    - name: namespace
      value: "default"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
