apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic
  namespace: demo
  labels:
    tekton.dev/pipelines: demo/springboot-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-clinic
  template:
    metadata:
      labels:
        app: pet-clinic
    spec:
      containers:
        - name: pet-clinic
          image: idpdeveacr.azurecr.io/pet-clinic:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pet-clinic
  namespace: demo
spec:
  selector:
    app: pet-clinic
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer