apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic
  namespace: demo
  annotations:
    backstage.io/ci-cd: enabled     # Enables Backstage integration   # Custom version annotation
    owner: team-devops             # Owner of the pipeline
    backstage.io/kubernetes-id: pet-clinic        # Matches the Kubernetes resources
    backstage.io/kubernetes-namespace: demo       # Namespace of the resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-clinic
  template:
    metadata:
      labels:
        app: pet-clinic
    spec:
      imagePullSecrets:
      - name: registry-auth
      containers:
        - name: pet-clinic
          image: idpdeveacr.azurecr.io/pet-clinic:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pet-clinic
  namespace: demo
spec:
  selector:
    app: pet-clinic
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer